---
apiVersion: v1
kind: Secret
metadata:
  name: azure-account-creds
  namespace:  crossplane-system
type: Opaque
data:
  credentials: ewogICJjbGllbnRJZCI6ICJhOGZhMTlmOS0zMjNjLTQ0OTQtOTc5ZC02ZjJhOTk5MDE0Y2QiLAogICJjbGllbnRTZWNyZXQiOiAiYkdkOFF+WE9TSGdOTmMycDBxZ2JYeHh2MWRhczNPWk5EZkFVX2N0NCIsCiAgInN1YnNjcmlwdGlvbklkIjogIjRhZmRhOGJhLTljZDctNDJhYS04MmY2LWYyYmQwM2U0MDNkYyIsCiAgInRlbmFudElkIjogImM1NGMyOTEzLTU2ZWItNGM4MC05YWY1LTUwNGQ4YjI2NmMzNSIsCiAgImFjdGl2ZURpcmVjdG9yeUVuZHBvaW50VXJsIjogImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsCiAgInJlc291cmNlTWFuYWdlckVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5henVyZS5jb20vIiwKICAiYWN0aXZlRGlyZWN0b3J5R3JhcGhSZXNvdXJjZUlkIjogImh0dHBzOi8vZ3JhcGgud2luZG93cy5uZXQvIiwKICAic3FsTWFuYWdlbWVudEVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5jb3JlLndpbmRvd3MubmV0Ojg0NDMvIiwKICAiZ2FsbGVyeUVuZHBvaW50VXJsIjogImh0dHBzOi8vZ2FsbGVyeS5henVyZS5jb20vIiwKICAibWFuYWdlbWVudEVuZHBvaW50VXJsIjogImh0dHBzOi8vbWFuYWdlbWVudC5jb3JlLndpbmRvd3MubmV0LyIKfQ==